version: '2'

services:
  gateway-config:
    build: .
    environment:
      - 'FIRMWARE_VERSION=2022.01.25.0'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT

  mqtt-broker:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - helium-sim-net

  provisioning-service:
    build: ./provisioning_service
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - helium-sim-net

volumes:
  miner-storage:

networks:
  helium-sim-net:
    driver: bridge
